(function () {
	'use strict';

	// This file is generated by Sapper — do not edit it!
	const timestamp = 1620465953406;

	const files = [
		"service-worker-index.html",
		"favicon.ico",
		"fonts/EuclidCircularA/EuclidCircularA-Bold.eot",
		"fonts/EuclidCircularA/EuclidCircularA-Bold.ttf",
		"fonts/EuclidCircularA/EuclidCircularA-Bold.woff",
		"fonts/EuclidCircularA/EuclidCircularA-Bold.woff2",
		"fonts/EuclidCircularA/EuclidCircularA-BoldItalic.eot",
		"fonts/EuclidCircularA/EuclidCircularA-BoldItalic.ttf",
		"fonts/EuclidCircularA/EuclidCircularA-BoldItalic.woff",
		"fonts/EuclidCircularA/EuclidCircularA-BoldItalic.woff2",
		"fonts/EuclidCircularA/EuclidCircularA-Italic.eot",
		"fonts/EuclidCircularA/EuclidCircularA-Italic.ttf",
		"fonts/EuclidCircularA/EuclidCircularA-Italic.woff",
		"fonts/EuclidCircularA/EuclidCircularA-Italic.woff2",
		"fonts/EuclidCircularA/EuclidCircularA-Light.eot",
		"fonts/EuclidCircularA/EuclidCircularA-Light.ttf",
		"fonts/EuclidCircularA/EuclidCircularA-Light.woff",
		"fonts/EuclidCircularA/EuclidCircularA-Light.woff2",
		"fonts/EuclidCircularA/EuclidCircularA-LightItalic.eot",
		"fonts/EuclidCircularA/EuclidCircularA-LightItalic.ttf",
		"fonts/EuclidCircularA/EuclidCircularA-LightItalic.woff",
		"fonts/EuclidCircularA/EuclidCircularA-LightItalic.woff2",
		"fonts/EuclidCircularA/EuclidCircularA-Medium.eot",
		"fonts/EuclidCircularA/EuclidCircularA-Medium.ttf",
		"fonts/EuclidCircularA/EuclidCircularA-Medium.woff",
		"fonts/EuclidCircularA/EuclidCircularA-Medium.woff2",
		"fonts/EuclidCircularA/EuclidCircularA-MediumItalic.eot",
		"fonts/EuclidCircularA/EuclidCircularA-MediumItalic.ttf",
		"fonts/EuclidCircularA/EuclidCircularA-MediumItalic.woff",
		"fonts/EuclidCircularA/EuclidCircularA-MediumItalic.woff2",
		"fonts/EuclidCircularA/EuclidCircularA-Regular.eot",
		"fonts/EuclidCircularA/EuclidCircularA-Regular.ttf",
		"fonts/EuclidCircularA/EuclidCircularA-Regular.woff",
		"fonts/EuclidCircularA/EuclidCircularA-Regular.woff2",
		"fonts/EuclidCircularA/EuclidCircularA-SemiBold.eot",
		"fonts/EuclidCircularA/EuclidCircularA-SemiBold.ttf",
		"fonts/EuclidCircularA/EuclidCircularA-SemiBold.woff",
		"fonts/EuclidCircularA/EuclidCircularA-SemiBold.woff2",
		"fonts/EuclidCircularA/EuclidCircularA-SemiBoldItalic.eot",
		"fonts/EuclidCircularA/EuclidCircularA-SemiBoldItalic.ttf",
		"fonts/EuclidCircularA/EuclidCircularA-SemiBoldItalic.woff",
		"fonts/EuclidCircularA/EuclidCircularA-SemiBoldItalic.woff2",
		"fonts/EuclidCircularA/typeface.css",
		"fonts/icons/icomoon.eot",
		"fonts/icons/icomoon.svg",
		"fonts/icons/icomoon.ttf",
		"fonts/icons/icomoon.woff",
		"fonts/icons.css",
		"img/autopublisher/advanced-removal-1.png",
		"img/autopublisher/bulk-publish.png",
		"img/autopublisher/control.png",
		"img/autopublisher/dashboard-unauthorized.png",
		"img/autopublisher/dashboard.png",
		"img/autopublisher/edit-profile.png",
		"img/autopublisher/list.png",
		"img/autopublisher/login.png",
		"img/autopublisher/settings-text.png",
		"img/autopublisher-mock.png",
		"img/betsense-mock.png",
		"img/icons/icon-192.png",
		"img/icons/icon-48.png",
		"img/icons/icon-512.png",
		"img/icons/icon-96.png",
		"manifest.json"
	];

	const shell = [
		"client/client.bd009450.js",
		"client/intersection-observer.8282416f.js",
		"client/index.7765a3df.js",
		"client/TransitionWrapper.e08df431.js",
		"client/Revealable.44c8021e.js",
		"client/Card.8e5541bb.js",
		"client/contact.630ce16e.js",
		"client/about.6526bb2a.js",
		"client/Scroller.52d1cc2c.js",
		"client/index.a6ef751d.js",
		"client/touch.ef1b2473.js",
		"client/autopublisher.aac26a37.js",
		"client/WorkHeader.65ef59dd.js",
		"client/betsense.f64044f7.js"
	];

	const ASSETS = `cache${timestamp}`;

	// `shell` is an array of all the files generated by the bundler,
	// `files` is an array of everything in the `static` directory
	const to_cache = shell.concat(files);
	const cached = new Set(to_cache);

	self.addEventListener('install', event => {
		event.waitUntil(
			caches
				.open(ASSETS)
				.then(cache => cache.addAll(to_cache))
				.then(() => {
					self.skipWaiting();
				})
		);
	});

	self.addEventListener('activate', event => {
		event.waitUntil(
			caches.keys().then(async keys => {
				// delete old caches
				for (const key of keys) {
					if (key !== ASSETS) await caches.delete(key);
				}

				self.clients.claim();
			})
		);
	});

	self.addEventListener('fetch', event => {
		if (event.request.method !== 'GET' || event.request.headers.has('range')) return;

		const url = new URL(event.request.url);

		// don't try to handle e.g. data: URIs
		if (!url.protocol.startsWith('http')) return;

		// ignore dev server requests
		if (url.hostname === self.location.hostname && url.port !== self.location.port) return;

		// always serve static files and bundler-generated assets from cache
		if (url.host === self.location.host && cached.has(url.pathname)) {
			event.respondWith(caches.match(event.request));
			return;
		}

		// for pages, you might want to serve a shell `service-worker-index.html` file,
		// which Sapper has generated for you. It's not right for every
		// app, but if it's right for yours then uncomment this section
		/*
		if (url.origin === self.origin && routes.find(route => route.pattern.test(url.pathname))) {
			event.respondWith(caches.match('/service-worker-index.html'));
			return;
		}
		*/

		if (event.request.cache === 'only-if-cached') return;

		// for everything else, try the network first, falling back to
		// cache if the user is offline. (If the pages never change, you
		// might prefer a cache-first approach to a network-first one.)
		event.respondWith(
			caches
				.open(`offline${timestamp}`)
				.then(async cache => {
					try {
						const response = await fetch(event.request);
						cache.put(event.request, response.clone());
						return response;
					} catch(err) {
						const response = await cache.match(event.request);
						if (response) return response;

						throw err;
					}
				})
		);
	});

}());
